export const EXTERNAL_LINKS = {
  faucet: 'https://faucet.xone.org/',
  docs: 'https://docs.xone.org/',
  TestnetExplorer: 'https://testnet.xscscan.com',
  MainExplorer: 'https://xscscan.com',
  Events: 'https://lu.ma/xone',
  Github: 'https://github.com/huione-labs',
  Twitter: 'https://x.com/xone_chain',
  Telegram: 'https://t.me/Xone_Group',
  TelegramDevelopers: 'https://t.me/Xone_Developers',
  Youtube: 'https://www.youtube.com/@HelloXone',
  Medium: 'https://medium.com/@xone_chain',
  Donate: 'https://knight.center/',
  DonateDocs: 'https://docs.knight.center/',
  Bridge: 'https://bridge.xonetest.plus/',
  TokenUp: 'https://tokenup.org/en',
  SwapX: 'https://swapx.exchange/en',
  RainLink: 'https://bridge.xonetest.plus/',
  Discord: 'https://discord.gg/Du9y2GHV',
  Suggest_Dapp:"https://github.com/huione-labs/docs/issues/new?template=suggest_dapp.yaml"
};
